CREATE TABLE BUS_DEPOT (
    DEPOTID INTEGER NOT NULL UNIQUE ,
    DEPOTNAME VARCHAR (255) NOT NULL PRIMARY KEY,
    DEPOTBUSES INTEGER ,
    BUSUPDATED TIMESTAMP
    PRIMARY KEY (DEPOTID),
)
CREATE TABLE BUSES (
    BUSID INTEGER NOT NULL UNIQUE,
    BUSNAME VARCHAR (255) NOT NULL,
    BUSNUMBER VARCHAR (255) NOT NULL,
    BUSTYPE VARCHAR (255),
    BUSCLASS VARCHAR (255),
    BUSSERVICESTARTED TIMESTAMP,
    PRIMARY KEY (BUSID),
    FOREIGN KEY (DEPOTID) REFERENCES BUS_DEPOT(DEPOTID)
)
--
